[package]
name = "e_ink_gallery_maker"
version = "0.1.0"
authors = ["YT"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.0"
clap = "2.33.3"
